upgrade to java 21
companieshouse/company-accounts.api.ch.gov.uk pull request #557
Opened 2024-03-22 15:09 UTC by nhill-ch

2024-04-10 16:11 UTC, akunati-ch commented
@nhill-ch , Can you update the README.md file with correct version please

2024-04-11 10:43 UTC, hwatkins-ch requested changes
Looks good, would like to avoid PR's this big in general though going forward :) 

Few comments around wildcard imports.

2024-04-11 10:43 UTC, hwatkins-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/CompanyAccountsApplicationTest.java
> +import org.mockito.*;
Wildcard import

2024-04-11 10:43 UTC, hwatkins-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/controller/CompanyAccountControllerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Wildcard import

2024-04-11 10:43 UTC, hwatkins-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/service/impl/CompanyAccountServiceImplTest.java
> +import java.util.*;
Wildcard import

2024-04-11 10:43 UTC, hwatkins-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/service/impl/FilingServiceImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Wildcard import

2024-04-11 10:43 UTC, hwatkins-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/validation/CreditorsWithinOneYearValidatorTests.java
> +import org.junit.jupiter.api.*;
Wildcard import

2024-04-11 10:43 UTC, hwatkins-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/validation/LoanValidatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Wildcard import

2024-04-11 10:43 UTC, hwatkins-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/validation/transactionclosure/PerviousPeriodTxnClosureValidatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Wildcard import

2024-04-11 10:43 UTC, hwatkins-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/validation/transactionclosure/StocksTxnClosureValidatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Wildcard import

2024-04-11 11:01 UTC, nhill-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/CompanyAccountsApplicationTest.java
> +import org.mockito.*;
done

2024-04-11 11:01 UTC, nhill-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/controller/CompanyAccountControllerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
done

2024-04-11 11:01 UTC, nhill-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/service/impl/CompanyAccountServiceImplTest.java
> +import java.util.*;
done

2024-04-11 11:01 UTC, nhill-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/service/impl/FilingServiceImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
done

2024-04-11 11:01 UTC, nhill-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/validation/CreditorsWithinOneYearValidatorTests.java
> +import org.junit.jupiter.api.*;
done

2024-04-11 11:01 UTC, nhill-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/validation/LoanValidatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
done

2024-04-11 11:01 UTC, nhill-ch commented on src/test/java/uk/gov/companieshouse/api/accounts/validation/transactionclosure/PerviousPeriodTxnClosureValidatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
done

2024-04-11 11:18 UTC, hwatkins-ch approved these changes

2024-04-12 08:08 UTC, akunati-ch approved these changes

2024-04-12 09:14 UTC, merged