Feature/dvop 3113 company accounts api ecs terraform update
companieshouse/company-accounts.api.ch.gov.uk pull request #583
Opened 2024-12-02 08:16 UTC by cryder-ch

2024-12-02 08:16 UTC, ch-code-analysis commented
CI: IaC Security warnings found!

2024-12-02 10:39 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-12-02 11:02 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-12-17 11:15 UTC, makhtar-ch commented on terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
> +log_level = "info"
If the log_level is defined in the [S3](https://github.com/companieshouse/ecs-service-configs-dev/blob/main/development-eu-west-2/cidev/company-accounts.api.ch.gov.uk.env) .env file, the log_level from these profile/vars can be removed.

2024-12-17 11:18 UTC, makhtar-ch requested changes

2024-12-17 11:18 UTC, makhtar-ch commented on terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
> +log_level = "info"
```suggestion

```
If the log_level is defined in the S3 .env file, the log_level from these profile/vars can be removed.

2024-12-17 11:18 UTC, makhtar-ch commented on terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
> +log_level = "info"
```suggestion

```
same here

2024-12-17 11:18 UTC, makhtar-ch commented on terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> +log_level = "info"
```suggestion

```
same here

2024-12-17 13:41 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-12-17 13:42 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-12-17 13:42 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-12-17 13:45 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-12-17 13:45 UTC, makhtar-ch approved these changes

2024-12-17 13:57 UTC, merged